### ISSUE TITLE
Add icons for more e-book formats

### ISSUE THREAD

**Issue by TmLev** [TmLev/dal#123]
Such as `.djvu`, `.epub`, `.fb2`, `.rtf`, ...

The relevant list of icons is [here](https://github.com/TmLev/dal/tree/c402c8f38835415cdf2d075d267ce3884d1988b0/front-end/src/assets/extensions-icon).

**Comment by gakhromov** [comment]
Can't live without `plaintext` and `.md`

**Comment by TmLev** [comment]
> Can't live without `plaintext` and `.md`

`plaintext` is `.txt`, which is present. 
I'm not sure that our clients use `.md` files, to be honest.
