### ISSUE TITLE
Auth users and Teachers/Students

### ISSUE THREAD

**Issue by gakhromov** [TmLev/dal#124]
It would be great to add teachers to the `Lesson` model (as it may happen that different teachers may conduct different lessons). However, adding a reference to the `Teacher` model would be incorrect. In the model `Subject`, discipline administrator is a `User` and `User`s are not connected to `Teacher`s or `Person`s in any way. Thus, it would be hard to insert teachers by default (which should actually be discipline administrators).

There are several possible solutions to this:

1. We could add a **`Teacher` reference to the `Subject` model** (or, even, make several references, which would be useful for cases when several teachers work on the same discipline), but it would break our abstraction rules. To deal with that, we would have to move `Teacher`s to our `common` app, with all `Milgroup`s, `Milfaculty`, `Rank`s and so on - not good.
2. We could try to **connect `Teacher`s to `User`s via foreign fields**. This means that when each `User` is created, he or she should be assigned some sort of type (teacher or student). This would make them have some default roles and would make handling cases from above a bit easier. It would still be a bit tough to reference `Teacher`s in `Lesson`s though, as the reference is not direct. Ok, we have a `User` reference. How can we get teachers from those? Maybe inheritance could help?.
3. The last option I see is to make **`Teacher`s inherit from `User`s**. I am a bit too tired to explain further, hope you get the idea.

Leave your ideas in the comments, if you have any.

This issue is not urgent, though it will come up later **definitely**. If we do not come up with some sort of solution to this, other people that will continue our work will certainly have to implement this. And they will. In the most buggy and clunky way possible.

**Comment by TmLev** [comment]
Currently, all Teachers have FK to User model which means second option was chosen at some moment.
All lessons now have FK to Teacher.
