### ISSUE TITLE
Notify `tgbot` on uniform update

### ISSUE THREAD

**Issue by TmLev** [TmLev/dal#269]
Full notification pipeline may look like so:
- [x] Milfaculty head updates the uniform in the `lms` app.
- [x] `lms` sends new uniform to `tgbot` upon receiving an update.
- [x] `tgbot` fetches all milgroup commanders from `lms`. 
- [x] `tgbot` messages every commander.

Such a feature requires `tgbot` to have a POST handler for uniform updates. This can be achieved by using `aiohttp` server in combination with `aiogram` bot dispatcher. An example can be found [here](https://github.com/aiogram/aiogram/pull/433/files).

**Comment by TmLev** [comment]
#271 took us halfway there.

**Comment by vladisa88** [comment]
We can do this in another, easier way:

- Add POST request for handling uniform updates
- In this request we can send request directly to TelegramBotAPI and send message from there
Inshallah
