### ISSUE TITLE
Models with primary key != id can't be `PATCH`ed

### ISSUE THREAD

**Issue by gakhromov** [TmLev/dal#282]
It is a django ~~bug~~ feature. If a model like this

```python
class Rank(models.Model):
    rank = models.CharField(primary_key=True, max_length=30)
```
 is `PATCH`ed, new instance is created and the old one remains. This could be fixed by introducing ids to the model and making them primary keys, whereas fields that were previously primary should be marked as unique.

**Comment by gakhromov** [comment]
Using `unique=True` instead of `primary_key=True` (as suggested by @vladisa88) is a good solution!

**Comment by vladisa88** [comment]
List of models with `primary_key` and `foreign_key` problems:

- `Achievement` and `AchievementType`
- `Teacher`, `Rank` and `TeacherPost`
- `Faculty`, `Program` and `UniversityInfo`
- `Milfaculty`, 'Milgroup`, `Milspeciality`
- `Lesson`, `Room`
