### ISSUE TITLE
drf-yasg incompatible with drf 3.12+

### ISSUE THREAD

**Issue by gakhromov** [TmLev/dal#50]
Latest version of django rest framework yasg (yet another Swagger generator) does not support django rest framework 3.12+ versions. 

I have fixed the issue by locking the drf version to ~=3.11.2 in the Pipfile.

Hopefully, drf-yasg will fix the issue. Or, at least, we might find another Swagger generator that supports newer drf versions.

**Comment by TmLev** [comment]
This issue in drf-yasg: [link](https://github.com/axnsan12/drf-yasg/issues/641).
A fork that will be (hopefully) maintained by others: [drf-yasg2](https://github.com/JoelLefkowitz/drf-yasg).
